# Example:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: activity-event-service
  namespace: internal-systems
  description: activity-event-service
  tags:
    - java
  links:
    - url: https://example.com
      title: URL to my app
      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: team-d
  providesApis:
    - activity-events
