# Example:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: server-backend-actvities-overview
  description: activities-overview
spec:
  type: service
  lifecycle: production
  owner: team-d
  system: activities-overview-system
  dependsOn: server-backend-weboffice-auth
  providesApis:
    - external/activity-api
    - external/user-api
    - external/vehicle-api
  consumesApis:
    - activity-event-api
    - customer-api
    - user-api
    - vehicle-api