# Example:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: server-backend-actvities-overview
  description: activities-overview
spec:
  type: service
  lifecycle: production
  owner: team-d
  system: activities-overview-system
  providesApis:
    - external/activities
    - external/users
    - external/vehicles
  consumesApis:
    - activity-event-api
    - customer-api
    - user-api
    - vehicle-api