# Example:
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: server-backend-actvities-overview
  description: activities-overview
spec:
  type: service
  lifecycle: production
  owner: team-d
  providesApis:
    - activities